image: ubuntu:20.04

pipelines:
  pull-requests:
    "**": # Run this by default
      - step:
          name: Build and test the C++ code
          script:
            - bash tools/install_common_dependencies.sh
            - bash tools/install_cpp_dependencies.sh
            - git submodule update --init --recursive
            - ./tools/build_project.sh
            - ./tools/install_project.sh
      - step:
          name: Build and test the Python code
          image: python:3.8-buster
          script:
            - bash tools/install_common_dependencies.sh
            - bash tools/install_python_dependencies.sh
            - export PATH="$HOME/.pyenv/bin:$PATH" # Add pyenv to the path
            - eval "$(pyenv init -)"
            - eval "$(pyenv virtualenv-init -)"
            - pyenv install 3.8.12 # Install python versions to test against
            - pyenv install 3.9.10
            - pyenv install 3.10.2
            - pyenv local 3.10.2 3.9.10 3.8.12 # Make python binaries available locally
            - export PATH="/root/.local/bin:$PATH" # Add poetry to the path
            - poetry install
            - nox
