[tool.poetry]
name = "last_letter_lib"
version = "2.1.0"
description = "Software libraries for UAV simulation."
authors = ["George Zogopoulos-Papaliakos <tailwhipx4@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
numpy = ">1.19.2,<1.22"
PyYAML = ">=5.3.1"
numba = "^0.55.2"
MarkupSafe = "2.0.1"
pytransform3d = "^1.14.0"
pydantic = "^1.10.4"
pcg-gazebo = {git = "https://github.com/boschresearch/pcg_gazebo.git", rev = "346394cdb720c9df5ca1d1df6dac7ad0b6e436fc"}
trimesh = "^3.23.3"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-cov = "^3.0.0"
pre-commit = "^2.19.0"
black = "^22.3.0"
isort = ">=5.10.1"
pre-commit-hooks = "^4.3.0"
pyupgrade = "^2.34.0"
flake8 = "^4.0.1"
flake8-bandit = "^3.0.0"
flake8-bugbear = "^22.4.25"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.2.6"
pep8-naming = "^0.13.0"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
]

[tool.coverage.paths]
source = ["src", "*/site-packages"]
tests = ["tests/python/*"]

[tool.coverage.run]
branch = true
source = ["last_letter_lib", "tests"]

[tool.coverage.report]
show_missing = true
fail_under = 90

[tool.isort]
profile = "black"
force_single_line = true
lines_after_imports = 2

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
