# HID configuration parameters
# All arrays must be 11 elements long
# Aileron, Elevator, Throttle and Rudder commands correspond to the positions 0, 1, 2 and 3 respectively.

joy2chan:
  ros__parameters:
    # Microsoft Sidewinder 2 joystick
    # Channel     [0      1     2     3     4     5     6     7     8     9    10  ]
    # axes:    [1,     2,    3,    0,   -1,   -1,    5,   -1,   -1,   -1,   -1  ]
    # buttons: [-1,   -1,   -1,   -1,   -1,    0,   -1,   -1,    1,    5,   -1  ]
    # throws:  [ 1.0, -1.0, -1.0, -1.0,  1.0,  1.0,  1.0,  0.0,  1.0,  1.0,  0.0]

    # E-Sky 0905A USB transmitter
    # Channel       [0      1      2      3     4      5     6     7     8     9    10  ]
    # axes:    [0,     1,     2,     4,    4,    -1,   -1,   -1,   -1,   -1,   -1  ]
    # buttons: [-1,   -1,    -1,    -1,   -1,    -1,   -1,   -1,   -1,   -1,   -1  ]
    # throws:  [0.66,  0.89, -0.85, 0.65, -0.65,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0]

    # Digital Element GM-400
    # axes: [4, 3, 1, 0, -1, -1, -1, -1, -1, -1, -1 ]
    # buttons: [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1 ]
    # throws: [-1.0, -1.0, 1.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]

    # Microsoft XBOX One controller
    # Channel [0      1     2     3     4     5     6     7     8     9    10  ]
    axes: [3, 4, 1, 0, -1, -1, 5, -1, -1, -1, -1]
    buttons: [-1, -1, -1, -1, -1, 0, -1, -1, 1, 5, -1]
    throws: [-1.0, -1.0, 1.0, -1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0]

    # Template
    # Channel       [0     1     2     3     4     5     6     7     8     9    10  ]
    # axes:    [-1,  -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1  ]
    # buttons: [-1,  -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1  ]
    # throws:  [0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0]

    # Mixer id number, see joy2chan.cpp code:
    # 0 for no mixing
    # 1 for airplane mixing
    # 2 for quadrotor mixing
    mixerid: 1
